# Generated by Django 5.1.2 on 2024-10-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
