# Generated by Django 5.1.2 on 2024-10-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_poster_full_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('created_events', models.ManyToManyField(related_name='poster', to='main_app.poster')),
            ],
        ),
    ]
