# Generated by Django 5.1.2 on 2024-10-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_password_alter_user_name_alter_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='background_image',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
