# Generated by Django 5.1.2 on 2024-10-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_user_password'),
        ('main_app', '0006_poster_background_image_alter_user_password'),
    ]

    operations = [
    ]
