# Generated by Django 5.1.2 on 2024-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_poster_price_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='slug',
            field=models.CharField(default='add', max_length=255),
            preserve_default=False,
        ),
    ]
