# Generated by Django 5.1.2 on 2024-10-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_poster_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=255, null=True),
        ),
    ]
