# Generated by Django 5.1.2 on 2024-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_poster_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='background_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='preview_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='time_event',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
