# Generated by Django 5.1.2 on 2024-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_poster_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
