# Generated by Django 5.1.2 on 2024-10-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_poster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='subscribers',
            field=models.ManyToManyField(related_name='user', to='main_app.user'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='time_event',
            field=models.DateTimeField(),
        ),
    ]
