# Generated by Django 5.1.2 on 2024-10-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='event',
            new_name='events',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='sender',
            new_name='senders',
        ),
    ]
